Update abseil (#357)
* Remove absl files

* Replace iresearch_absl to absl

* Replace ::irs::absl with ::absl

* Fix process count for icu-build

* Fix compilation error: move forgotten

* Replace runtime assert with static_assert

* Add abseil-cpp submodule

* Add abseil as external dependency

* Use absl::Hash instead of some internal stuff

* Fix cmake for abseil

* Use patch for abseil on windows